### ISSUE TITLE
[Bug]: Move from Heroku to Replit for proxy

### ISSUE THREAD

**Issue by arjunj132** [bhagavdgita/bhagavdgita.github.io#7]
### Contact Details

jakkipally@gmail.com

### What did you expect?

The Verse of the Day to load properly

### What actually happend?

It is stuck on `Loading... Please wait`

This issue is created because the [proxy](https://proxy-for-cors.herokuapp.com/) to open the Replit is based on Heroku, and has an error and will not go to the main Replit flask app which creates a random verse each day.

Ways to prevent:
1. Use a Replit-based proxy, like this one [here](https://proxy.arjunjakkipally.repl.co/)
2. Enable CORS on the flask app

### Version

0 (pre-release)

### What operating system are you using?

Developer - Universal

### What OS version are you using?

Universal (Chrome)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kitakitaaura** [comment]
Updated CORS on flask app.

**Comment by kitakitaaura** [comment]
Updated official build with verse of the day updated to not use proxy

**Comment by kitakitaaura** [comment]
Works in the universal version properly. I am closing this issue, but if happening again, it can be reopened.
