### ISSUE TITLE
[Bug]: Share verse of the day will not work

### ISSUE THREAD

**Issue by arjunj132** [bhagavdgita/bhagavdgita.github.io#8]
### What did you expect?

I expected a share dialog to open on Verse of the Day.

### What actually happend?

Nothing happened at all

### Version

0 (pre-release)

### What operating system are you using?

Android

### What OS version are you using?

Android 13 (Tiramisu)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kitakitaaura** [comment]
This looks like an issue with the Android Webview. It does not support navigator.share. I will look into this.

**Comment by kitakitaaura** [comment]
The prompt works on iOS properly.

**Comment by kitakitaaura** [comment]
Look at this issue: https://github.com/react-native-webview/react-native-webview/issues/1262#issuecomment-930469321

It has a solution in Kotlin. I will try and see if it works.

**Comment by kitakitaaura** [comment]
I can't run the solution. I will try and use a polyfill.

This one looks good: https://github.com/on2-dev/share-api-polyfill

**Comment by kitakitaaura** [comment]
It looks like it will work. It will keep the original if it is supported. Let me try it on the official copy.

**Comment by kitakitaaura** [comment]
I think it worked. It is still in maintenance mode though. I will test further.

**Comment by kitakitaaura** [comment]
Some of the options not working due to only https:// and http:// being supported. Let's try opening them in a new tab.

**Comment by kitakitaaura** [comment]
We cannot use the polyfill because it calls non-HTTP/HTTPS URLs. I will probably just delete the share option. Anyway, who will really share it?

**Comment by kitakitaaura** [comment]
Actually, I checked the source code for the polyfill, and it uses `window.open`. The android webview does not support this. Let me try using the details from https://stackoverflow.com/questions/9147875/webview-dont-display-javascript-windows-open

**Comment by kitakitaaura** [comment]
It is in Java, and the app is in Kotlin, so I cannot do it. Let me look into the apps that don't work and those that do work.

**Comment by kitakitaaura** [comment]
I can't do anything about this. So what I will do is just delete it. I might look into the future of native apps for android.
