### ISSUE TITLE
[Feature Request]: Clean GitHub into folder

### ISSUE THREAD

**Issue by arjunj132** [bhagavdgita/bhagavdgita.github.io#9]
### What do you want improved or added?

I need the GitHub stuff into folders, as we need to clean up everything. A lot of stuff is just crammed up into the GitHub's root, and we need to organize it.

### Version

0 (pre-release)

### What operating system are you using?

Developer - Universal

### What OS version are you using?

iOS 7 and below, iOS 8, iOS 9, iOS 10, iOS 11, iOS 12, iOS 13, iOS 14, iOS 15, iOS 16 (beta), Android KitKat and below, Android Lollipop, Android Marshmallow, Android Nougat, Android Oreo, Android Pie, Android 10 (Android Q), Android 11 (Red Velvet Cake), Android 12 (Snow Cone), Android 13 (Tiramisu), Universal (Chrome), Universal (Safari)

### Code of Conduct

- [x] #10

**Comment by kitakitaaura** [comment]
We have cleaned and updated the app.
